name: fullsend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  appinio_swiper: ^2.1.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  path_provider: ^2.1.2
  provider: ^6.1.1
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sl.png
    - assets/r.png
    - assets/l.png
    - assets/c.png
    - assets/b.png
    - assets/love.png
    - assets/tinder.png
    - assets/dm.png
    - assets/user.png
    - assets/home.png
    - assets/shake.png
    - assets/shake hand.png
